spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  #设置开启热部署
  devtools:
    restart:
      enabled: true
  #页面加载
  thymeleaf:
    cache:false
#端口
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml